### ISSUE TITLE
Compiler run failed: Error (2314): Expected '=>' but got identifier

### ISSUE THREAD

**Issue by RaphaelMagnux** [defi-wonderland/solidity-foundry-boilerplate#85]
**Description**

Error found at the moment to build project, appears that '_chainId' has not been found.

**Reproducing error**

`$ yarn build`

Then appears this.

<img width="635" alt="Screenshot 2024-10-05 at 10 11 22 a m" src="https://github.com/user-attachments/assets/a588cbef-a3ae-4ddc-befb-bbeb7171074f">

**Comment by gas1cent** [comment]
Thanks for the report. The error is due to the version of Solidity used to compile the code, because the named mapping parameters were introduced in 0.8.18.

**Comment by RaphaelMagnux** [comment]
Thank you for the aclaration!
