### ISSUE TITLE
Linter throwing "Function name must be in mixedCase" for `bulloak` generated test names 

### ISSUE THREAD

**Issue by RonTuretzky** [defi-wonderland/solidity-foundry-boilerplate#90]
For example, in Greeter.t.sol , the tests are not mixedCase. Can this be fixed in the solhint?

**Comment by 0xteddybear** [comment]
Hello @RonTuretzky , thanks for reporting this :heart_hands: 

> Can this be fixed in the solhint?

yes!  we actually implemented it in https://github.com/defi-wonderland/solidity-foundry-boilerplate/pull/82 , where we configured `style-guide-casing` to ignore the casing of contracts and external and public functions, via a configuration file exclusive to the `tests/` subdirectory. 

Are you sure you are using the latest version of the boilerplate? If updating doesn't fix your issue, please provide:

- your `solhint-community` version in your `package.json`
- your top-level `solhint.json`
- your `tests/.solhint.json`

And a snippet of code under  `test/` that causes the linter to error/warn, so we can help you troubleshoot your issue

**Comment by RonTuretzky** [comment]
Cherry picked the commit into our codebase and it still shows the same error...

for all the tests in the unit folder we're getting messages like these 

```
[{
	"resource": "/<>/test/unit/<>",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 4,
	"message": "Linter: Function name must be in mixedCase [func-name-mixedcase]",
	"startLineNumber": 65,
	"startColumn": 3,
	"endLineNumber": 65,
	"endColumn": 4
}]
```

**Comment by RonTuretzky** [comment]
`git cherry-pick <#82 commithash>` fixed the issue!
